// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Welcome',
    },
    {
      type: 'doc',
      id: 'tutorial-first-integration',
      label: 'Tutorial — first integration',
    },
    {
      type: 'doc',
      id: 'integration-guide',
      label: 'Integration Guide',
    },
    {
      type: 'category',
      label: 'DataBridge',
      items: [
        {
          type: 'autogenerated',
          dirName: 'databridge',
        },
      ],
    },
    {
      type: 'category',
      label: 'SmartLink',
      items: [
        {
          type: 'autogenerated',
          dirName: 'smartlink',
        },
      ],
    },
    {
      type: 'category',
      label: 'BillSense AI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'billsense-ai',
        },
      ],
    },
    {
      type: 'category',
      label: 'PIX (Instant Payments)',
      items: [
        {
          type: 'doc',
          id: 'pix/about-pix',
          label: 'About PIX',
        },
        {
          type: 'doc',
          id: 'pix/tutorial-first-payment',
          label: 'Tutorial — first payment',
        },
        {
          type: 'doc',
          id: 'pix/how-to-handle-webhooks',
          label: 'How-to — webhooks',
        },
        {
          type: 'category',
          label: 'API reference',
          items: [
            {
              type: 'doc',
              id: 'api/pix-api/instant-payments-api-pix-sample',
              label: 'Overview',
            },
            {
              type: 'category',
              label: 'Charges',
              items: [
                {
                  type: 'doc',
                  id: 'api/pix-api/create-charge',
                  label: 'Create charge',
                  className: 'api-method put',
                },
                {
                  type: 'doc',
                  id: 'api/pix-api/get-charge',
                  label: 'Get charge',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/pix-api/update-charge',
                  label: 'Update charge',
                  className: 'api-method patch',
                },
              ],
            },
            {
              type: 'category',
              label: 'Received payments',
              items: [
                {
                  type: 'doc',
                  id: 'api/pix-api/get-received-pix',
                  label: 'Get received PIX',
                  className: 'api-method get',
                },
              ],
            },
            {
              type: 'category',
              label: 'Webhooks',
              items: [
                {
                  type: 'doc',
                  id: 'api/pix-api/register-webhook',
                  label: 'Register webhook',
                  className: 'api-method put',
                },
                {
                  type: 'doc',
                  id: 'api/pix-api/get-webhook',
                  label: 'Get webhook',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/pix-api/delete-webhook',
                  label: 'Delete webhook',
                  className: 'api-method delete',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'api/powerbox-api',
          label: 'Overview',
        },
        {
          type: 'category',
          label: 'Customer',
          items: [
            {
              type: 'doc',
              id: 'api/sync-customer',
              label: 'Customer Synchronization',
            },
          ],
        },
        {
          type: 'category',
          label: 'Hardware',
          items: [
            {
              type: 'doc',
              id: 'api/bind-device',
              label: 'Hardware Binding',
            },
          ],
        },
        {
          type: 'category',
          label: 'Usage API',
          items: [
            {
              type: 'doc',
              id: 'api/usage-api/energygrid-usage-api',
              label: 'Overview',
            },
            {
              type: 'category',
              label: 'Customer',
              items: [
                {
                  type: 'doc',
                  id: 'api/usage-api/customer-login',
                  label: 'Login',
                  className: 'api-method post',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/get-customer-info',
                  label: 'Get Customer Info',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/get-budget',
                  label: 'Get Budget',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/set-budget',
                  label: 'Set Budget',
                  className: 'api-method post',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/get-home-profile',
                  label: 'Get Home Profile',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/update-home-profile',
                  label: 'Update Home Profile',
                  className: 'api-method post',
                },
              ],
            },
            {
              type: 'category',
              label: 'Insights',
              items: [
                {
                  type: 'doc',
                  id: 'api/usage-api/get-dig-deeper',
                  label: 'Dig Deeper',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/get-main-uses-of-energy',
                  label: 'Main Uses of Energy',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/get-message-carousel',
                  label: 'Message Carousel',
                  className: 'api-method get',
                },
              ],
            },
            {
              type: 'category',
              label: 'Similar Homes',
              items: [
                {
                  type: 'doc',
                  id: 'api/usage-api/get-similar-homes',
                  label: 'Similar Homes Comparison',
                  className: 'api-method get',
                },
              ],
            },
            {
              type: 'category',
              label: 'Usage',
              items: [
                {
                  type: 'doc',
                  id: 'api/usage-api/filter-usage',
                  label: 'Filter Usage',
                  className: 'api-method get',
                },
              ],
            },
            {
              type: 'category',
              label: 'Metadata',
              items: [
                {
                  type: 'doc',
                  id: 'api/usage-api/get-thing-types',
                  label: 'Get Thing Types',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/get-thing-categories',
                  label: 'Get Thing Categories',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/get-granularity-types',
                  label: 'Get Granularity Types',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/get-property-types',
                  label: 'Get Property Types',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/get-metric-types',
                  label: 'Get Metric Types',
                  className: 'api-method get',
                },
              ],
            },
            {
              type: 'category',
              label: 'Rate Data',
              items: [
                {
                  type: 'doc',
                  id: 'api/usage-api/get-rate-groups',
                  label: 'Get Rate Groups',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'api/usage-api/get-billing-cycle-dates',
                  label: 'Get Billing Cycle Dates',
                  className: 'api-method get',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'doc',
      id: 'data-dictionary/data-dictionary',
      label: 'Data Dictionary',
    },
    {
      type: 'doc',
      id: 'writing-guideline',
      label: 'Writing Guideline',
    },
    {
      type: 'doc',
      id: 'methodology',
      label: 'Methodology',
    },
    {
      type: 'category',
      label: 'About this site',
      items: [
        {
          type: 'doc',
          id: 'using-these-docs-with-ai',
          label: 'Using these docs with AI',
        },
        {
          type: 'category',
          label: 'Architecture decision records',
          items: [
            {
              type: 'doc',
              id: 'adr/index',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'adr/001-docusaurus-over-mkdocs',
              label: 'ADR-001 — Docusaurus over MkDocs',
            },
            {
              type: 'doc',
              id: 'adr/002-google-style-over-microsoft',
              label: 'ADR-002 — Google over Microsoft style',
            },
            {
              type: 'doc',
              id: 'adr/003-diataxis-as-page-taxonomy',
              label: 'ADR-003 — Diátaxis taxonomy',
            },
            {
              type: 'doc',
              id: 'adr/004-vale-fail-on-error',
              label: 'ADR-004 — Vale fail-on-error',
            },
            {
              type: 'doc',
              id: 'adr/005-openapi-as-source-of-truth',
              label: 'ADR-005 — OpenAPI source of truth',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
